/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Database.Koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author MDena
 */

public class Home extends javax.swing.JFrame {

    public Home() {
        initComponents();
        Label1_21552011440.setHorizontalAlignment(SwingConstants.CENTER);
        Label1_21552011440.setVerticalAlignment(SwingConstants.CENTER);
        Label2_21552011440.setHorizontalAlignment(SwingConstants.CENTER);
        Label2_21552011440.setVerticalAlignment(SwingConstants.CENTER);
        Label3_21552011440.setHorizontalAlignment(SwingConstants.CENTER);
        Label3_21552011440.setVerticalAlignment(SwingConstants.CENTER);
        
        MenuMaster_21552011440.setEnabled(false);
        MenuTransaksi_21552011440.setEnabled(false);
        MenuLaporan_21552011440.setEnabled(false);
        MenuLogout_21552011440.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginLogout_21552011440 = new javax.swing.JDialog();
        PanelLogin_21552011440 = new javax.swing.JPanel();
        LabelUsername_21552011440 = new javax.swing.JLabel();
        LabelPassword_21552011440 = new javax.swing.JLabel();
        TextFieldUN_21552011440 = new javax.swing.JTextField();
        LabelLogin_21552011440 = new javax.swing.JLabel();
        ButtonLogin_21552011440 = new javax.swing.JButton();
        ButtonCancel_21552011440 = new javax.swing.JButton();
        TextFieldPW_21552011440 = new javax.swing.JPasswordField();
        Register_21552011440 = new javax.swing.JDialog();
        PanelRegister_21552011440 = new javax.swing.JPanel();
        LabelUsername2_21552011440 = new javax.swing.JLabel();
        LabelPassword2_21552011440 = new javax.swing.JLabel();
        TextFieldPW2_21552011440 = new javax.swing.JTextField();
        TextFieldUN2_21552011440 = new javax.swing.JTextField();
        LabelLogin2_21552011440 = new javax.swing.JLabel();
        ButtonrRegister_21552011440 = new javax.swing.JButton();
        ButtonCancel2_21552011440 = new javax.swing.JButton();
        LabelNamaLengkap_21552011440 = new javax.swing.JLabel();
        TextFieldNL_21552011440 = new javax.swing.JTextField();
        DesktopPane_21552011440 = new javax.swing.JDesktopPane();
        Label1_21552011440 = new javax.swing.JLabel();
        Label2_21552011440 = new javax.swing.JLabel();
        Label3_21552011440 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuBar_21552011440 = new javax.swing.JMenuBar();
        MenuHome_21552011440 = new javax.swing.JMenu();
        MenuItemLogin_21552011440 = new javax.swing.JMenuItem();
        MenuItemRegister_21552011440 = new javax.swing.JMenuItem();
        MenuMaster_21552011440 = new javax.swing.JMenu();
        MenuItemPelanggan_21552011440 = new javax.swing.JMenuItem();
        MenuItemBarang_21552011440 = new javax.swing.JMenuItem();
        MenuTransaksi_21552011440 = new javax.swing.JMenu();
        MenuItemPenjualan_21552011440 = new javax.swing.JMenuItem();
        MenuItemPembelian_21552011440 = new javax.swing.JMenuItem();
        MenuLaporan_21552011440 = new javax.swing.JMenu();
        MenuItemL_21552011440 = new javax.swing.JMenuItem();
        MenuLogout_21552011440 = new javax.swing.JMenu();

        LoginLogout_21552011440.setLocation(new java.awt.Point(512, 310));
        LoginLogout_21552011440.setMinimumSize(new java.awt.Dimension(402, 300));

        PanelLogin_21552011440.setBackground(new java.awt.Color(0, 204, 204));

        LabelUsername_21552011440.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        LabelUsername_21552011440.setText("Username");

        LabelPassword_21552011440.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        LabelPassword_21552011440.setText("Password");

        LabelLogin_21552011440.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        LabelLogin_21552011440.setText("Login");

        ButtonLogin_21552011440.setText("Log In");
        ButtonLogin_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogin_21552011440ActionPerformed(evt);
            }
        });

        ButtonCancel_21552011440.setText("Cancel");
        ButtonCancel_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancel_21552011440ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLogin_21552011440Layout = new javax.swing.GroupLayout(PanelLogin_21552011440);
        PanelLogin_21552011440.setLayout(PanelLogin_21552011440Layout);
        PanelLogin_21552011440Layout.setHorizontalGroup(
            PanelLogin_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogin_21552011440Layout.createSequentialGroup()
                .addGroup(PanelLogin_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLogin_21552011440Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(LabelLogin_21552011440))
                    .addGroup(PanelLogin_21552011440Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(PanelLogin_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldUN_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(TextFieldPW_21552011440))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelLogin_21552011440Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(PanelLogin_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelPassword_21552011440)
                    .addComponent(ButtonLogin_21552011440)
                    .addComponent(LabelUsername_21552011440))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(ButtonCancel_21552011440)
                .addGap(84, 84, 84))
        );
        PanelLogin_21552011440Layout.setVerticalGroup(
            PanelLogin_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLogin_21552011440Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelLogin_21552011440)
                .addGap(53, 53, 53)
                .addGroup(PanelLogin_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldUN_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelUsername_21552011440))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(PanelLogin_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPassword_21552011440)
                    .addComponent(TextFieldPW_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PanelLogin_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancel_21552011440)
                    .addComponent(ButtonLogin_21552011440))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout LoginLogout_21552011440Layout = new javax.swing.GroupLayout(LoginLogout_21552011440.getContentPane());
        LoginLogout_21552011440.getContentPane().setLayout(LoginLogout_21552011440Layout);
        LoginLogout_21552011440Layout.setHorizontalGroup(
            LoginLogout_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLogin_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LoginLogout_21552011440Layout.setVerticalGroup(
            LoginLogout_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLogin_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Register_21552011440.setLocation(new java.awt.Point(512, 310));
        Register_21552011440.setMinimumSize(new java.awt.Dimension(402, 300));

        PanelRegister_21552011440.setBackground(new java.awt.Color(0, 204, 204));

        LabelUsername2_21552011440.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        LabelUsername2_21552011440.setText("Username");

        LabelPassword2_21552011440.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        LabelPassword2_21552011440.setText("Password");

        LabelLogin2_21552011440.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        LabelLogin2_21552011440.setText("Register");

        ButtonrRegister_21552011440.setText("Register");
        ButtonrRegister_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonrRegister_21552011440ActionPerformed(evt);
            }
        });

        ButtonCancel2_21552011440.setText("Cancel");
        ButtonCancel2_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancel2_21552011440ActionPerformed(evt);
            }
        });

        LabelNamaLengkap_21552011440.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        LabelNamaLengkap_21552011440.setText("Nama Lengkap");

        javax.swing.GroupLayout PanelRegister_21552011440Layout = new javax.swing.GroupLayout(PanelRegister_21552011440);
        PanelRegister_21552011440.setLayout(PanelRegister_21552011440Layout);
        PanelRegister_21552011440Layout.setHorizontalGroup(
            PanelRegister_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegister_21552011440Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(ButtonrRegister_21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonCancel2_21552011440)
                .addGap(81, 81, 81))
            .addGroup(PanelRegister_21552011440Layout.createSequentialGroup()
                .addGroup(PanelRegister_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegister_21552011440Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(LabelLogin2_21552011440))
                    .addGroup(PanelRegister_21552011440Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(PanelRegister_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRegister_21552011440Layout.createSequentialGroup()
                                .addComponent(LabelNamaLengkap_21552011440)
                                .addGap(194, 194, 194))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegister_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextFieldNL_21552011440, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(TextFieldUN2_21552011440, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TextFieldPW2_21552011440, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(PanelRegister_21552011440Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(PanelRegister_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelUsername2_21552011440)
                            .addComponent(LabelPassword2_21552011440))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        PanelRegister_21552011440Layout.setVerticalGroup(
            PanelRegister_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegister_21552011440Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelLogin2_21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(PanelRegister_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNamaLengkap_21552011440)
                    .addComponent(TextFieldNL_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegister_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelUsername2_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldUN2_21552011440))
                .addGap(18, 18, 18)
                .addGroup(PanelRegister_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPassword2_21552011440)
                    .addGroup(PanelRegister_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFieldPW2_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(PanelRegister_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancel2_21552011440)
                    .addComponent(ButtonrRegister_21552011440))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout Register_21552011440Layout = new javax.swing.GroupLayout(Register_21552011440.getContentPane());
        Register_21552011440.getContentPane().setLayout(Register_21552011440Layout);
        Register_21552011440Layout.setHorizontalGroup(
            Register_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegister_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Register_21552011440Layout.setVerticalGroup(
            Register_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegister_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));

        Label1_21552011440.setBackground(new java.awt.Color(0, 0, 0));
        Label1_21552011440.setForeground(new java.awt.Color(0, 204, 204));
        Label1_21552011440.setText("Created By MUHAMMAD DENA");

        Label2_21552011440.setBackground(new java.awt.Color(0, 0, 0));
        Label2_21552011440.setForeground(new java.awt.Color(0, 204, 204));
        Label2_21552011440.setText("21552011440");

        Label3_21552011440.setBackground(new java.awt.Color(0, 0, 0));
        Label3_21552011440.setForeground(new java.awt.Color(0, 204, 204));
        Label3_21552011440.setText("TIF RP 21C");

        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("<HTML>\n<P>HARAP TUTUP FORM SEBELUM LOGOUT!!!!<P>\n</HTML>");

        DesktopPane_21552011440.setLayer(Label1_21552011440, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane_21552011440.setLayer(Label2_21552011440, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane_21552011440.setLayer(Label3_21552011440, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane_21552011440.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPane_21552011440Layout = new javax.swing.GroupLayout(DesktopPane_21552011440);
        DesktopPane_21552011440.setLayout(DesktopPane_21552011440Layout);
        DesktopPane_21552011440Layout.setHorizontalGroup(
            DesktopPane_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopPane_21552011440Layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addGroup(DesktopPane_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label1_21552011440)
                    .addGroup(DesktopPane_21552011440Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(DesktopPane_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label3_21552011440)
                            .addComponent(Label2_21552011440))))
                .addGap(318, 318, 318))
        );
        DesktopPane_21552011440Layout.setVerticalGroup(
            DesktopPane_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPane_21552011440Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(Label1_21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label2_21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label3_21552011440)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        MenuBar_21552011440.setBackground(new java.awt.Color(0, 204, 204));

        MenuHome_21552011440.setText("HOME");

        MenuItemLogin_21552011440.setText("Login");
        MenuItemLogin_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogin_21552011440ActionPerformed(evt);
            }
        });
        MenuHome_21552011440.add(MenuItemLogin_21552011440);

        MenuItemRegister_21552011440.setText("Register");
        MenuItemRegister_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemRegister_21552011440ActionPerformed(evt);
            }
        });
        MenuHome_21552011440.add(MenuItemRegister_21552011440);

        MenuBar_21552011440.add(MenuHome_21552011440);

        MenuMaster_21552011440.setText("MASTER");

        MenuItemPelanggan_21552011440.setText("Pelanggan");
        MenuItemPelanggan_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPelanggan_21552011440ActionPerformed(evt);
            }
        });
        MenuMaster_21552011440.add(MenuItemPelanggan_21552011440);

        MenuItemBarang_21552011440.setText("Barang");
        MenuItemBarang_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemBarang_21552011440ActionPerformed(evt);
            }
        });
        MenuMaster_21552011440.add(MenuItemBarang_21552011440);

        MenuBar_21552011440.add(MenuMaster_21552011440);

        MenuTransaksi_21552011440.setText("TRANSAKSI");

        MenuItemPenjualan_21552011440.setText("Penjualan");
        MenuItemPenjualan_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPenjualan_21552011440ActionPerformed(evt);
            }
        });
        MenuTransaksi_21552011440.add(MenuItemPenjualan_21552011440);

        MenuItemPembelian_21552011440.setText("Pembelian");
        MenuItemPembelian_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPembelian_21552011440ActionPerformed(evt);
            }
        });
        MenuTransaksi_21552011440.add(MenuItemPembelian_21552011440);

        MenuBar_21552011440.add(MenuTransaksi_21552011440);

        MenuLaporan_21552011440.setText("LAPORAN");

        MenuItemL_21552011440.setText("Laporan");
        MenuItemL_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemL_21552011440ActionPerformed(evt);
            }
        });
        MenuLaporan_21552011440.add(MenuItemL_21552011440);

        MenuBar_21552011440.add(MenuLaporan_21552011440);

        MenuLogout_21552011440.setText("LOGOUT");
        MenuLogout_21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLogout_21552011440MouseClicked(evt);
            }
        });
        MenuLogout_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogout_21552011440ActionPerformed(evt);
            }
        });
        MenuBar_21552011440.add(MenuLogout_21552011440);

        setJMenuBar(MenuBar_21552011440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DesktopPane_21552011440)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane_21552011440)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLogin_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogin_21552011440ActionPerformed
        try{
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_aplikasi_penjualan","root","");
            Statement stat = koneksi.createStatement();
            ResultSet rs=stat.executeQuery("select count(username)from user where username='"+TextFieldUN_21552011440.getText()+"'and password='"+TextFieldPW_21552011440.getText()+"'");
            if(rs.next()){
                int username=rs.getInt(1);
                if(username>0){
                    MenuMaster_21552011440.setEnabled(true);
                    MenuTransaksi_21552011440.setEnabled(true);
                    MenuLaporan_21552011440.setEnabled(true);
                    MenuLogout_21552011440.setEnabled(true);
                    MenuItemRegister_21552011440.setEnabled(false);
                    MenuItemLogin_21552011440.setEnabled(false);
                    LoginLogout_21552011440.setVisible(false);
                    TextFieldUN_21552011440.setText("");
                    TextFieldPW_21552011440.setText("");
                }else{
                    JOptionPane.showMessageDialog(null,"Username/Password Salah!!!");                    
                    TextFieldUN_21552011440.setText("");
                    TextFieldPW_21552011440.setText("");
                }
                
            }
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_ButtonLogin_21552011440ActionPerformed

    private void ButtonCancel_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancel_21552011440ActionPerformed
    TextFieldUN_21552011440.setText("");
    TextFieldPW_21552011440.setText("");
    LoginLogout_21552011440.setVisible(false);
    }//GEN-LAST:event_ButtonCancel_21552011440ActionPerformed

    private void ButtonrRegister_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonrRegister_21552011440ActionPerformed
     try {
            String sql = "INSERT INTO user VALUES ('"+TextFieldNL_21552011440.getText()+"','"
                    +TextFieldUN2_21552011440.getText()+"','"
                    +TextFieldPW2_21552011440.getText()+"')";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil DiMasukan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }                   
    TextFieldNL_21552011440.setText("");
    TextFieldUN2_21552011440.setText("");
    TextFieldPW2_21552011440.setText("");
    }//GEN-LAST:event_ButtonrRegister_21552011440ActionPerformed

    private void ButtonCancel2_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancel2_21552011440ActionPerformed
    TextFieldNL_21552011440.setText("");
    TextFieldUN2_21552011440.setText("");
    TextFieldPW2_21552011440.setText("");
    Register_21552011440.setVisible(false);
    }//GEN-LAST:event_ButtonCancel2_21552011440ActionPerformed

    private void MenuItemRegister_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemRegister_21552011440ActionPerformed
    Register_21552011440.setVisible(true);
    }//GEN-LAST:event_MenuItemRegister_21552011440ActionPerformed

    private void MenuItemLogin_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogin_21552011440ActionPerformed
    LoginLogout_21552011440.setVisible(true);
    }//GEN-LAST:event_MenuItemLogin_21552011440ActionPerformed

    private void MenuLogout_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogout_21552011440ActionPerformed
   
    }//GEN-LAST:event_MenuLogout_21552011440ActionPerformed

    private void MenuLogout_21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLogout_21552011440MouseClicked
    Master.Pelanggan MP = new Master.Pelanggan();
    Master.Barang MB = new Master.Barang();
    Transaksi.Pembelian TP1 = new Transaksi.Pembelian();
    Transaksi.Penjualan TP2 = new Transaksi.Penjualan();
    DesktopPane_21552011440.add(MP);
    MP.setVisible(false);        
    MenuHome_21552011440.setEnabled(true);
    MenuItemRegister_21552011440.setEnabled(true);
    MenuItemLogin_21552011440.setEnabled(true);
    MenuMaster_21552011440.setEnabled(false);
    MenuTransaksi_21552011440.setEnabled(false);
    MenuLaporan_21552011440.setEnabled(false);
    MenuLogout_21552011440.setEnabled(false);
    }//GEN-LAST:event_MenuLogout_21552011440MouseClicked

    private void MenuItemPelanggan_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPelanggan_21552011440ActionPerformed
     Master.Pelanggan MP = new Master.Pelanggan();
     DesktopPane_21552011440.add(MP);
     MP.setVisible(true);
    }//GEN-LAST:event_MenuItemPelanggan_21552011440ActionPerformed

    private void MenuItemBarang_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBarang_21552011440ActionPerformed
     Master.Barang MB = new Master.Barang();
     DesktopPane_21552011440.add(MB);
     MB.setVisible(true);
    }//GEN-LAST:event_MenuItemBarang_21552011440ActionPerformed

    private void MenuItemPenjualan_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPenjualan_21552011440ActionPerformed
     Transaksi.Penjualan TP2 = new Transaksi.Penjualan();
     DesktopPane_21552011440.add(TP2);
     TP2.setVisible(true);
    }//GEN-LAST:event_MenuItemPenjualan_21552011440ActionPerformed

    private void MenuItemL_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemL_21552011440ActionPerformed
     Laporan.Laporan LP = new Laporan.Laporan();
     DesktopPane_21552011440.add(LP);
     LP.setVisible(true);
    }//GEN-LAST:event_MenuItemL_21552011440ActionPerformed

    private void MenuItemPembelian_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPembelian_21552011440ActionPerformed
     Transaksi.Pembelian TP1 = new Transaksi.Pembelian();
     DesktopPane_21552011440.add(TP1);
     TP1.setVisible(true);
    }//GEN-LAST:event_MenuItemPembelian_21552011440ActionPerformed

    public Home(JDesktopPane desktop){
        initComponents();
        this.DesktopPane_21552011440 = desktop;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel2_21552011440;
    private javax.swing.JButton ButtonCancel_21552011440;
    private javax.swing.JButton ButtonLogin_21552011440;
    private javax.swing.JButton ButtonrRegister_21552011440;
    private javax.swing.JDesktopPane DesktopPane_21552011440;
    private javax.swing.JLabel Label1_21552011440;
    private javax.swing.JLabel Label2_21552011440;
    private javax.swing.JLabel Label3_21552011440;
    private javax.swing.JLabel LabelLogin2_21552011440;
    private javax.swing.JLabel LabelLogin_21552011440;
    private javax.swing.JLabel LabelNamaLengkap_21552011440;
    private javax.swing.JLabel LabelPassword2_21552011440;
    private javax.swing.JLabel LabelPassword_21552011440;
    private javax.swing.JLabel LabelUsername2_21552011440;
    private javax.swing.JLabel LabelUsername_21552011440;
    private javax.swing.JDialog LoginLogout_21552011440;
    private javax.swing.JMenuBar MenuBar_21552011440;
    private javax.swing.JMenu MenuHome_21552011440;
    private javax.swing.JMenuItem MenuItemBarang_21552011440;
    private javax.swing.JMenuItem MenuItemL_21552011440;
    private javax.swing.JMenuItem MenuItemLogin_21552011440;
    private javax.swing.JMenuItem MenuItemPelanggan_21552011440;
    private javax.swing.JMenuItem MenuItemPembelian_21552011440;
    private javax.swing.JMenuItem MenuItemPenjualan_21552011440;
    private javax.swing.JMenuItem MenuItemRegister_21552011440;
    private javax.swing.JMenu MenuLaporan_21552011440;
    private javax.swing.JMenu MenuLogout_21552011440;
    private javax.swing.JMenu MenuMaster_21552011440;
    private javax.swing.JMenu MenuTransaksi_21552011440;
    private javax.swing.JPanel PanelLogin_21552011440;
    private javax.swing.JPanel PanelRegister_21552011440;
    private javax.swing.JDialog Register_21552011440;
    private javax.swing.JTextField TextFieldNL_21552011440;
    private javax.swing.JTextField TextFieldPW2_21552011440;
    private javax.swing.JPasswordField TextFieldPW_21552011440;
    private javax.swing.JTextField TextFieldUN2_21552011440;
    private javax.swing.JTextField TextFieldUN_21552011440;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
