/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Laporan;

import Database.Koneksi;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author MDena
 */
public class Laporan extends javax.swing.JInternalFrame {

    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
        TabelPelanggan();
        TabelBarang();
        TabelTTB();
        TabelTTJ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabelPelanggan = new javax.swing.JDialog();
        PanelTP_21552011440 = new javax.swing.JPanel();
        LabelTP_21552011440 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_Pelanggan_21552011440 = new javax.swing.JTable();
        ButtonExportTP_21552011440 = new javax.swing.JButton();
        TabelBarang = new javax.swing.JDialog();
        PanelTB_21552011440 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBL_Barang_21552011440 = new javax.swing.JTable();
        LabelTB_21552011440 = new javax.swing.JLabel();
        ButtonExportTB_21552011440 = new javax.swing.JButton();
        TabelTransaksiBeli = new javax.swing.JDialog();
        PanelTTB_21552011440 = new javax.swing.JPanel();
        LabelTTB_21552011440 = new javax.swing.JLabel();
        ButtonExportTTB_21552011440 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TBL_Pembelian_21552011440 = new javax.swing.JTable();
        TabelTransaksiJual = new javax.swing.JDialog();
        PanelTTJ_21552011440 = new javax.swing.JPanel();
        LabelTTJ_21552011440 = new javax.swing.JLabel();
        ButtonExportTTJ_21552011440 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBL_Penjualan_21552011440 = new javax.swing.JTable();
        PanelLaporan_21552011440 = new javax.swing.JPanel();
        ButtonTP_21552011440 = new javax.swing.JButton();
        ButtonTB_21552011440 = new javax.swing.JButton();
        ButtonTTB_21552011440 = new javax.swing.JButton();
        ButtonTTJ_21552011440 = new javax.swing.JButton();
        LabelLaporan_21552011440 = new javax.swing.JLabel();

        TabelPelanggan.setAlwaysOnTop(true);
        TabelPelanggan.setLocation(new java.awt.Point(35, 55));
        TabelPelanggan.setMinimumSize(new java.awt.Dimension(450, 350));

        LabelTP_21552011440.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        LabelTP_21552011440.setText("Tabel Pelanggan");

        TBL_Pelanggan_21552011440.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pelanggan", "Nama", "Jenis Kelamin", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBL_Pelanggan_21552011440.setEnabled(false);
        TBL_Pelanggan_21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_Pelanggan_21552011440MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_Pelanggan_21552011440);

        ButtonExportTP_21552011440.setText("Export Excel");
        ButtonExportTP_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExportTP_21552011440ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTP_21552011440Layout = new javax.swing.GroupLayout(PanelTP_21552011440);
        PanelTP_21552011440.setLayout(PanelTP_21552011440Layout);
        PanelTP_21552011440Layout.setHorizontalGroup(
            PanelTP_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTP_21552011440Layout.createSequentialGroup()
                .addGroup(PanelTP_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTP_21552011440Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                    .addGroup(PanelTP_21552011440Layout.createSequentialGroup()
                        .addGroup(PanelTP_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTP_21552011440Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(LabelTP_21552011440))
                            .addGroup(PanelTP_21552011440Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(ButtonExportTP_21552011440)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelTP_21552011440Layout.setVerticalGroup(
            PanelTP_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTP_21552011440Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTP_21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonExportTP_21552011440)
                .addContainerGap())
        );

        javax.swing.GroupLayout TabelPelangganLayout = new javax.swing.GroupLayout(TabelPelanggan.getContentPane());
        TabelPelanggan.getContentPane().setLayout(TabelPelangganLayout);
        TabelPelangganLayout.setHorizontalGroup(
            TabelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTP_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TabelPelangganLayout.setVerticalGroup(
            TabelPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTP_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabelBarang.setAlwaysOnTop(true);
        TabelBarang.setLocation(new java.awt.Point(40, 60));
        TabelBarang.setMinimumSize(new java.awt.Dimension(450, 350));

        TBL_Barang_21552011440.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "QTY", "Harga Beli", "Harga Jual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBL_Barang_21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_Barang_21552011440MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBL_Barang_21552011440);

        LabelTB_21552011440.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        LabelTB_21552011440.setText("Tabel Barang");

        ButtonExportTB_21552011440.setText("Export Excel");
        ButtonExportTB_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExportTB_21552011440ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTB_21552011440Layout = new javax.swing.GroupLayout(PanelTB_21552011440);
        PanelTB_21552011440.setLayout(PanelTB_21552011440Layout);
        PanelTB_21552011440Layout.setHorizontalGroup(
            PanelTB_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTB_21552011440Layout.createSequentialGroup()
                .addGroup(PanelTB_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTB_21552011440Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(PanelTB_21552011440Layout.createSequentialGroup()
                        .addGroup(PanelTB_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTB_21552011440Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(LabelTB_21552011440))
                            .addGroup(PanelTB_21552011440Layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(ButtonExportTB_21552011440)))
                        .addGap(0, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelTB_21552011440Layout.setVerticalGroup(
            PanelTB_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTB_21552011440Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTB_21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(ButtonExportTB_21552011440)
                .addContainerGap())
        );

        javax.swing.GroupLayout TabelBarangLayout = new javax.swing.GroupLayout(TabelBarang.getContentPane());
        TabelBarang.getContentPane().setLayout(TabelBarangLayout);
        TabelBarangLayout.setHorizontalGroup(
            TabelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTB_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TabelBarangLayout.setVerticalGroup(
            TabelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTB_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabelTransaksiBeli.setAlwaysOnTop(true);
        TabelTransaksiBeli.setLocation(new java.awt.Point(45, 65));
        TabelTransaksiBeli.setMinimumSize(new java.awt.Dimension(920, 375));

        LabelTTB_21552011440.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        LabelTTB_21552011440.setText("Tabel Transaksi Beli");

        ButtonExportTTB_21552011440.setText("Export Excel");
        ButtonExportTTB_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExportTTB_21552011440ActionPerformed(evt);
            }
        });

        TBL_Pembelian_21552011440.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal Pembelian", "No Transaksi", "ID Pelanggan", "Nama Pelanggan", "Kode Barang", "Nama Barang", "Stock", "Harga Awal", "Jumlah Beli", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBL_Pembelian_21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_Pembelian_21552011440MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TBL_Pembelian_21552011440);

        javax.swing.GroupLayout PanelTTB_21552011440Layout = new javax.swing.GroupLayout(PanelTTB_21552011440);
        PanelTTB_21552011440.setLayout(PanelTTB_21552011440Layout);
        PanelTTB_21552011440Layout.setHorizontalGroup(
            PanelTTB_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTTB_21552011440Layout.createSequentialGroup()
                .addGroup(PanelTTB_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTTB_21552011440Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(PanelTTB_21552011440Layout.createSequentialGroup()
                        .addGroup(PanelTTB_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTTB_21552011440Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(LabelTTB_21552011440))
                            .addGroup(PanelTTB_21552011440Layout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(ButtonExportTTB_21552011440)))
                        .addGap(0, 401, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelTTB_21552011440Layout.setVerticalGroup(
            PanelTTB_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTTB_21552011440Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTTB_21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonExportTTB_21552011440)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TabelTransaksiBeliLayout = new javax.swing.GroupLayout(TabelTransaksiBeli.getContentPane());
        TabelTransaksiBeli.getContentPane().setLayout(TabelTransaksiBeliLayout);
        TabelTransaksiBeliLayout.setHorizontalGroup(
            TabelTransaksiBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTTB_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TabelTransaksiBeliLayout.setVerticalGroup(
            TabelTransaksiBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTTB_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabelTransaksiJual.setAlwaysOnTop(true);
        TabelTransaksiJual.setLocation(new java.awt.Point(50, 70));
        TabelTransaksiJual.setMinimumSize(new java.awt.Dimension(960, 350));

        LabelTTJ_21552011440.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        LabelTTJ_21552011440.setText("Tabel Transaksi Jual");

        ButtonExportTTJ_21552011440.setText("Export Excel");
        ButtonExportTTJ_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExportTTJ_21552011440ActionPerformed(evt);
            }
        });

        TBL_Penjualan_21552011440.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal Penjualan", "No Transaksi", "ID Pelanggan", "Nama Pelanggan", "Kode Barang", "Nama Barang", "Stock", "Harga Satuan", "Jumlah Jual", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBL_Penjualan_21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_Penjualan_21552011440MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TBL_Penjualan_21552011440);

        javax.swing.GroupLayout PanelTTJ_21552011440Layout = new javax.swing.GroupLayout(PanelTTJ_21552011440);
        PanelTTJ_21552011440.setLayout(PanelTTJ_21552011440Layout);
        PanelTTJ_21552011440Layout.setHorizontalGroup(
            PanelTTJ_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTTJ_21552011440Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(LabelTTJ_21552011440)
                .addContainerGap(642, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTTJ_21552011440Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonExportTTJ_21552011440)
                .addGap(371, 371, 371))
            .addGroup(PanelTTJ_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTTJ_21552011440Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3)
                    .addContainerGap()))
        );
        PanelTTJ_21552011440Layout.setVerticalGroup(
            PanelTTJ_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTTJ_21552011440Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTTJ_21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(ButtonExportTTJ_21552011440)
                .addContainerGap())
            .addGroup(PanelTTJ_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelTTJ_21552011440Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout TabelTransaksiJualLayout = new javax.swing.GroupLayout(TabelTransaksiJual.getContentPane());
        TabelTransaksiJual.getContentPane().setLayout(TabelTransaksiJualLayout);
        TabelTransaksiJualLayout.setHorizontalGroup(
            TabelTransaksiJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTTJ_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TabelTransaksiJualLayout.setVerticalGroup(
            TabelTransaksiJualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTTJ_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        ButtonTP_21552011440.setText("Tabel Pelanggan");
        ButtonTP_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTP_21552011440ActionPerformed(evt);
            }
        });

        ButtonTB_21552011440.setText("Tabel Barang");
        ButtonTB_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTB_21552011440ActionPerformed(evt);
            }
        });

        ButtonTTB_21552011440.setText("Tabel Transaksi Beli");
        ButtonTTB_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTTB_21552011440ActionPerformed(evt);
            }
        });

        ButtonTTJ_21552011440.setText("Tabel Transaksi Jual");
        ButtonTTJ_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTTJ_21552011440ActionPerformed(evt);
            }
        });

        LabelLaporan_21552011440.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        LabelLaporan_21552011440.setText("Laporan");

        javax.swing.GroupLayout PanelLaporan_21552011440Layout = new javax.swing.GroupLayout(PanelLaporan_21552011440);
        PanelLaporan_21552011440.setLayout(PanelLaporan_21552011440Layout);
        PanelLaporan_21552011440Layout.setHorizontalGroup(
            PanelLaporan_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLaporan_21552011440Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(PanelLaporan_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ButtonTTJ_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonTTB_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonTB_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonTP_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(130, 130, 130))
            .addGroup(PanelLaporan_21552011440Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(LabelLaporan_21552011440)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLaporan_21552011440Layout.setVerticalGroup(
            PanelLaporan_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLaporan_21552011440Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelLaporan_21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ButtonTP_21552011440)
                .addGap(18, 18, 18)
                .addComponent(ButtonTB_21552011440)
                .addGap(18, 18, 18)
                .addComponent(ButtonTTB_21552011440)
                .addGap(18, 18, 18)
                .addComponent(ButtonTTJ_21552011440)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLaporan_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLaporan_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBL_Pelanggan_21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_Pelanggan_21552011440MouseClicked
     
    }//GEN-LAST:event_TBL_Pelanggan_21552011440MouseClicked

    private void TBL_Barang_21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_Barang_21552011440MouseClicked
   
    }//GEN-LAST:event_TBL_Barang_21552011440MouseClicked

    private void ButtonExportTTJ_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExportTTJ_21552011440ActionPerformed
        FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("[B]export_output/excel[/B]"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try{
                TableModel tModel = TBL_Penjualan_21552011440.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));           
            // write header
                for(int i = 0; i < tModel.getColumnCount(); i++){
                fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
            }
                fileWriter.write("\n");
            // write record
                for(int i=0; i < tModel.getRowCount(); i++) {
                for(int j=0; j < tModel.getColumnCount(); j++) {
                fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
            }
                fileWriter.write("\n");
            }
                fileWriter.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_ButtonExportTTJ_21552011440ActionPerformed

    private void ButtonExportTTB_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExportTTB_21552011440ActionPerformed
        FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("[B]export_output/excel[/B]"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try{
                TableModel tModel = TBL_Pembelian_21552011440.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));           
            // write header
                for(int i = 0; i < tModel.getColumnCount(); i++){
                fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
            }
                fileWriter.write("\n");
            // write record
                for(int i=0; i < tModel.getRowCount(); i++) {
                for(int j=0; j < tModel.getColumnCount(); j++) {
                fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
            }
                fileWriter.write("\n");
            }
                fileWriter.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_ButtonExportTTB_21552011440ActionPerformed

    private void ButtonExportTB_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExportTB_21552011440ActionPerformed
    FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("[B]export_output/excel[/B]"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try{
                TableModel tModel = TBL_Barang_21552011440.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));           
            // write header
                for(int i = 0; i < tModel.getColumnCount(); i++){
                fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
            }
                fileWriter.write("\n");
            // write record
                for(int i=0; i < tModel.getRowCount(); i++) {
                for(int j=0; j < tModel.getColumnCount(); j++) {
                fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
            }
                fileWriter.write("\n");
            }
                fileWriter.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_ButtonExportTB_21552011440ActionPerformed

    private void ButtonExportTP_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExportTP_21552011440ActionPerformed
     FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("[B]export_output/excel[/B]"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try{
                TableModel tModel = TBL_Pelanggan_21552011440.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));           
            // write header
                for(int i = 0; i < tModel.getColumnCount(); i++){
                fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
            }
                fileWriter.write("\n");
            // write record
                for(int i=0; i < tModel.getRowCount(); i++) {
                for(int j=0; j < tModel.getColumnCount(); j++) {
                fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
            }
                fileWriter.write("\n");
            }
                fileWriter.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_ButtonExportTP_21552011440ActionPerformed

    private void ButtonTP_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTP_21552011440ActionPerformed
    TabelPelanggan.setVisible(true);
    }//GEN-LAST:event_ButtonTP_21552011440ActionPerformed

    private void ButtonTB_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTB_21552011440ActionPerformed
    TabelBarang.setVisible(true);
    }//GEN-LAST:event_ButtonTB_21552011440ActionPerformed

    private void ButtonTTB_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTTB_21552011440ActionPerformed
    TabelTransaksiBeli.setVisible(true);
    }//GEN-LAST:event_ButtonTTB_21552011440ActionPerformed

    private void ButtonTTJ_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTTJ_21552011440ActionPerformed
    TabelTransaksiJual.setVisible(true);
    }//GEN-LAST:event_ButtonTTJ_21552011440ActionPerformed

    private void TBL_Pembelian_21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_Pembelian_21552011440MouseClicked
       
    }//GEN-LAST:event_TBL_Pembelian_21552011440MouseClicked

    private void TBL_Penjualan_21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_Penjualan_21552011440MouseClicked
       
    }//GEN-LAST:event_TBL_Penjualan_21552011440MouseClicked

     
        public final void TabelPelanggan() {
        DefaultTableModel model = new DefaultTableModel();
        TBL_Pelanggan_21552011440.setModel(model);
        model.addColumn("ID Pelanggan");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM pelanggan";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[4];
                o[0] = r.getString("id_pelanggan");
                o[1] = r.getString("nama");
                o[2] = r.getString("jenis_kelamin");
                o[3] = r.getString("alamat");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
   }
        public final void TabelBarang() {
        DefaultTableModel model = new DefaultTableModel();
        TBL_Barang_21552011440.setModel(model);
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Stock");
        model.addColumn("Harga Awal");
        model.addColumn("Harga Satuan");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM barang";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[5];
                o[0] = r.getString("kode_barang");
                o[1] = r.getString("nama_barang");
                o[2] = r.getObject("stock");
                o[3] = r.getString("harga_awal");
                o[4] = r.getString("harga_satuan");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
   }
        public final void TabelTTB() {
        DefaultTableModel model = new DefaultTableModel();
        TBL_Pembelian_21552011440.setModel(model);
        model.addColumn("Tanggal Pembelian");
        model.addColumn("No Transaksi");
        model.addColumn("ID Pelanggan");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Stock");
        model.addColumn("Harga Awal");
        model.addColumn("Jumlah Beli");
        model.addColumn("Total Harga");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM transaksi_beli";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[10];
                o[0] = r.getString("tanggal_pembelian");
                o[1] = r.getString("no_transaksi");
                o[2] = r.getString("id_pelanggan");
                o[3] = r.getString("nama_pelanggan");
                o[4] = r.getString("kode_barang");
                o[5] = r.getString("nama_barang");
                o[6] = r.getString("stock");
                o[7] = r.getObject("harga_awal");
                o[8] = r.getString("jumlah_beli");
                o[9] = r.getString("total_harga");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
   }
        public final void TabelTTJ() {
        DefaultTableModel model = new DefaultTableModel();
        TBL_Penjualan_21552011440.setModel(model);
        model.addColumn("Tanggal Penjualan");
        model.addColumn("No Transaksi");
        model.addColumn("ID Pelanggan");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Stock");
        model.addColumn("Harga Satuan");
        model.addColumn("Jumlah Jual");
        model.addColumn("Total Harga");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM transaksi_jual";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[10];
                o[0] = r.getString("tanggal_penjualan");
                o[1] = r.getString("no_transaksi");
                o[2] = r.getString("id_pelanggan");
                o[3] = r.getString("nama_pelanggan");
                o[4] = r.getString("kode_barang");
                o[5] = r.getString("nama_barang");
                o[6] = r.getString("stock");
                o[7] = r.getObject("harga_satuan");
                o[8] = r.getString("jumlah_jual");
                o[9] = r.getString("total_harga");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonExportTB_21552011440;
    private javax.swing.JButton ButtonExportTP_21552011440;
    private javax.swing.JButton ButtonExportTTB_21552011440;
    private javax.swing.JButton ButtonExportTTJ_21552011440;
    private javax.swing.JButton ButtonTB_21552011440;
    private javax.swing.JButton ButtonTP_21552011440;
    private javax.swing.JButton ButtonTTB_21552011440;
    private javax.swing.JButton ButtonTTJ_21552011440;
    private javax.swing.JLabel LabelLaporan_21552011440;
    private javax.swing.JLabel LabelTB_21552011440;
    private javax.swing.JLabel LabelTP_21552011440;
    private javax.swing.JLabel LabelTTB_21552011440;
    private javax.swing.JLabel LabelTTJ_21552011440;
    private javax.swing.JPanel PanelLaporan_21552011440;
    private javax.swing.JPanel PanelTB_21552011440;
    private javax.swing.JPanel PanelTP_21552011440;
    private javax.swing.JPanel PanelTTB_21552011440;
    private javax.swing.JPanel PanelTTJ_21552011440;
    private javax.swing.JTable TBL_Barang_21552011440;
    private javax.swing.JTable TBL_Pelanggan_21552011440;
    private javax.swing.JTable TBL_Pembelian_21552011440;
    private javax.swing.JTable TBL_Penjualan_21552011440;
    private javax.swing.JDialog TabelBarang;
    private javax.swing.JDialog TabelPelanggan;
    private javax.swing.JDialog TabelTransaksiBeli;
    private javax.swing.JDialog TabelTransaksiJual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
