/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Database.Koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MDena
 */
public class Penjualan extends javax.swing.JInternalFrame {

    /**
     * Creates new form Penjualan
     */
    public Penjualan() {
        initComponents();
        loadData();
        AutoID();
        loadTB();
        TampilCBID();
        TampilCBKB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabelBarang = new javax.swing.JDialog();
        PanelTB_21552011440 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBL_Barang_21552011440 = new javax.swing.JTable();
        LabelTB_21552011440 = new javax.swing.JLabel();
        Panel_21552011440 = new javax.swing.JPanel();
        LabelJudul_21552011440 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_Penjualan_21552011440 = new javax.swing.JTable();
        LabelNT_21552011440 = new javax.swing.JLabel();
        NT_TextField_21552011440 = new javax.swing.JTextField();
        ButtonTambah_21552011440 = new javax.swing.JButton();
        ButtonEdit_21552011440 = new javax.swing.JButton();
        ButtonHapus_21552011440 = new javax.swing.JButton();
        IDP_ComboBox_21552011440 = new javax.swing.JComboBox<>();
        LabelIDP_21552011440 = new javax.swing.JLabel();
        NP_TextField_21552011440 = new javax.swing.JTextField();
        LabelHS_21552011440 = new javax.swing.JLabel();
        LabelStock_21552011440 = new javax.swing.JLabel();
        LabelNB_21552011440 = new javax.swing.JLabel();
        LabelKDB_21552011440 = new javax.swing.JLabel();
        KB_ComboBox_21552011440 = new javax.swing.JComboBox<>();
        ButtonLB_21552011440 = new javax.swing.JButton();
        LabelINP_21552011440 = new javax.swing.JLabel();
        JJ_TextField_21552011440 = new javax.swing.JTextField();
        LabelJJ_21552011440 = new javax.swing.JLabel();
        LabelTPen_77174961 = new javax.swing.JLabel();
        LabelTH_21552011440 = new javax.swing.JLabel();
        TH_TextField_21552011440 = new javax.swing.JTextField();
        ButtonTotal_21552011440 = new javax.swing.JButton();
        HS_TextField_21552011440 = new javax.swing.JTextField();
        Stock_TextField_21552011440 = new javax.swing.JTextField();
        NB_TextField_21552011440 = new javax.swing.JTextField();
        CD_TextField_21552011440 = new javax.swing.JTextField();
        LabelCD_21552011440 = new javax.swing.JLabel();
        LabelInfo_21552011440 = new javax.swing.JLabel();
        dateChooserCombo_21552011440 = new datechooser.beans.DateChooserCombo();

        TabelBarang.setAlwaysOnTop(true);
        TabelBarang.setMinimumSize(new java.awt.Dimension(480, 350));

        TBL_Barang_21552011440.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "QTY", "Harga Beli", "Harga Jual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TBL_Barang_21552011440);

        LabelTB_21552011440.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        LabelTB_21552011440.setText("Tabel Barang");

        javax.swing.GroupLayout PanelTB_21552011440Layout = new javax.swing.GroupLayout(PanelTB_21552011440);
        PanelTB_21552011440.setLayout(PanelTB_21552011440Layout);
        PanelTB_21552011440Layout.setHorizontalGroup(
            PanelTB_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTB_21552011440Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(LabelTB_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(165, 165, 165))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTB_21552011440Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        PanelTB_21552011440Layout.setVerticalGroup(
            PanelTB_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTB_21552011440Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTB_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TabelBarangLayout = new javax.swing.GroupLayout(TabelBarang.getContentPane());
        TabelBarang.getContentPane().setLayout(TabelBarangLayout);
        TabelBarangLayout.setHorizontalGroup(
            TabelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTB_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        TabelBarangLayout.setVerticalGroup(
            TabelBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTB_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        LabelJudul_21552011440.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        LabelJudul_21552011440.setText("Data Penjualan");

        TBL_Penjualan_21552011440.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal Penjualan", "No Transaksi", "ID Pelanggan", "Nama Pelanggan", "Kode Barang", "Nama Barang", "Stock", "Harga Satuan", "Jumlah Jual", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBL_Penjualan_21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_Penjualan_21552011440MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_Penjualan_21552011440);

        LabelNT_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelNT_21552011440.setText("No Transaksi");

        ButtonTambah_21552011440.setText("Tambah");
        ButtonTambah_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambah_21552011440ActionPerformed(evt);
            }
        });

        ButtonEdit_21552011440.setText("Edit");
        ButtonEdit_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEdit_21552011440ActionPerformed(evt);
            }
        });

        ButtonHapus_21552011440.setText("Hapus");
        ButtonHapus_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapus_21552011440ActionPerformed(evt);
            }
        });

        IDP_ComboBox_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDP_ComboBox_21552011440ActionPerformed(evt);
            }
        });

        LabelIDP_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelIDP_21552011440.setText("ID Pelanggan");

        NP_TextField_21552011440.setEditable(false);

        LabelHS_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelHS_21552011440.setText("Harga Satuan");

        LabelStock_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelStock_21552011440.setText("Stock");

        LabelNB_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelNB_21552011440.setText("Nama Barang");

        LabelKDB_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelKDB_21552011440.setText("Kode Barang");

        KB_ComboBox_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KB_ComboBox_21552011440ActionPerformed(evt);
            }
        });

        ButtonLB_21552011440.setText("Lihat Barang");
        ButtonLB_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLB_21552011440ActionPerformed(evt);
            }
        });

        LabelINP_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelINP_21552011440.setText("Nama Pelanggan");

        LabelJJ_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelJJ_21552011440.setText("Jumlah Jual");

        LabelTPen_77174961.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelTPen_77174961.setText("Tanggal Pembelian");

        LabelTH_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelTH_21552011440.setText("Total Harga");

        TH_TextField_21552011440.setEditable(false);

        ButtonTotal_21552011440.setText("Total");
        ButtonTotal_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTotal_21552011440ActionPerformed(evt);
            }
        });

        HS_TextField_21552011440.setEditable(false);

        Stock_TextField_21552011440.setEditable(false);

        NB_TextField_21552011440.setEditable(false);

        CD_TextField_21552011440.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CD_TextField_21552011440KeyReleased(evt);
            }
        });

        LabelCD_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelCD_21552011440.setText("Cari Data");

        LabelInfo_21552011440.setText("<html>\n<p>Harap buka ulang form ini</p><br></br>\n<p>Untuk update ID Pelanggan dan Kode Barang</p><br></br>\n<p>Setelah input data di Pelanggan dan Barang</p><br></br>\n<p>Mohon maaf dan terima kasih</p>");

        dateChooserCombo_21552011440.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));

    javax.swing.GroupLayout Panel_21552011440Layout = new javax.swing.GroupLayout(Panel_21552011440);
    Panel_21552011440.setLayout(Panel_21552011440Layout);
    Panel_21552011440Layout.setHorizontalGroup(
        Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1)
        .addGroup(Panel_21552011440Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LabelKDB_21552011440)
                .addComponent(LabelIDP_21552011440)
                .addComponent(LabelNB_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(LabelStock_21552011440)
                .addComponent(LabelHS_21552011440)
                .addComponent(LabelJJ_21552011440)
                .addComponent(LabelINP_21552011440)
                .addComponent(LabelTPen_77174961)
                .addComponent(LabelTH_21552011440)
                .addComponent(LabelNT_21552011440))
            .addGap(18, 18, 18)
            .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_21552011440Layout.createSequentialGroup()
                    .addComponent(TH_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(ButtonTotal_21552011440))
                .addGroup(Panel_21552011440Layout.createSequentialGroup()
                    .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(KB_ComboBox_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NB_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Stock_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HS_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JJ_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Panel_21552011440Layout.createSequentialGroup()
                            .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NT_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(IDP_ComboBox_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NP_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateChooserCombo_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(70, 70, 70)
                            .addComponent(LabelInfo_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(213, 213, 213)
                    .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ButtonEdit_21552011440, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonTambah_21552011440, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonHapus_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_21552011440Layout.createSequentialGroup()
                            .addComponent(ButtonLB_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addGap(5, 5, 5)))))
            .addGap(81, 81, 81))
        .addGroup(Panel_21552011440Layout.createSequentialGroup()
            .addGap(231, 231, 231)
            .addComponent(LabelJudul_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LabelCD_21552011440)
            .addGap(18, 18, 18)
            .addComponent(CD_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(34, 34, 34))
    );
    Panel_21552011440Layout.setVerticalGroup(
        Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(Panel_21552011440Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(LabelJudul_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(CD_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(LabelCD_21552011440))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_21552011440Layout.createSequentialGroup()
                    .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Panel_21552011440Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelNT_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NT_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelIDP_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(IDP_ComboBox_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelINP_21552011440)
                                .addComponent(NP_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(Panel_21552011440Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(LabelInfo_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelKDB_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(KB_ComboBox_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelNB_21552011440)
                        .addComponent(NB_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelStock_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Stock_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelHS_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HS_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelJJ_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JJ_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Panel_21552011440Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dateChooserCombo_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelTPen_77174961, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addComponent(ButtonLB_21552011440)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonTambah_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(ButtonEdit_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(ButtonHapus_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(LabelTH_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(TH_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ButtonTotal_21552011440))
            .addContainerGap(77, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Panel_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 16, Short.MAX_VALUE)
            .addComponent(Panel_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTambah_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambah_21552011440ActionPerformed
        try {
            String sql = "INSERT INTO transaksi_jual VALUES ('"+dateChooserCombo_21552011440.getText()+"','"
            +NT_TextField_21552011440.getText()+"','"
            +IDP_ComboBox_21552011440.getSelectedItem()+"','"
            +NP_TextField_21552011440.getText()+"','"        
            +KB_ComboBox_21552011440.getSelectedItem()+"','"
            +NB_TextField_21552011440.getText()+"','"
            +Stock_TextField_21552011440.getText()+"','"
            +HS_TextField_21552011440.getText()+"','"
            +JJ_TextField_21552011440.getText()+"','"
            +TH_TextField_21552011440.getText()+"')";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        NT_TextField_21552011440.setEnabled(true);
        loadData();
        AutoID();
        Bersih();
    }//GEN-LAST:event_ButtonTambah_21552011440ActionPerformed

    private void IDP_ComboBox_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDP_ComboBox_21552011440ActionPerformed
    TampilNP();
    }//GEN-LAST:event_IDP_ComboBox_21552011440ActionPerformed

    private void ButtonLB_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLB_21552011440ActionPerformed
        TabelBarang.setVisible(true);
        loadTB();
    }//GEN-LAST:event_ButtonLB_21552011440ActionPerformed

    private void KB_ComboBox_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KB_ComboBox_21552011440ActionPerformed
    TampilNB();
    TampilStock();
    TampilHarga();
    }//GEN-LAST:event_KB_ComboBox_21552011440ActionPerformed

    private void ButtonHapus_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapus_21552011440ActionPerformed
    try {
            String sql ="delete from transaksi_jual where no_transaksi='"+NT_TextField_21552011440.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    NT_TextField_21552011440.setEnabled(true);
    loadData();
    AutoID();
    Bersih();
    }//GEN-LAST:event_ButtonHapus_21552011440ActionPerformed

    private void ButtonEdit_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEdit_21552011440ActionPerformed
    try {
            String sql ="UPDATE transaksi_jual SET tanggal_penjualan = '"+dateChooserCombo_21552011440.getText()+
                    "',no_transaksi = '"+NT_TextField_21552011440.getText()+
                    "',id_pelanggan = '"+IDP_ComboBox_21552011440.getSelectedItem()+
                    "',nama_pelanggan= '"+NP_TextField_21552011440.getText()+
                    "',kode_barang= '"+KB_ComboBox_21552011440.getSelectedItem()+
                    "',nama_barang= '"+NB_TextField_21552011440.getText()+
                    "',stock= '"+Stock_TextField_21552011440.getText()+
                    "',harga_satuan= '"+HS_TextField_21552011440.getText()+
                    "',jumlah_jual= '"+JJ_TextField_21552011440.getText()+
                    "',total_harga= '"+TH_TextField_21552011440.getText()+
                    "' WHERE no_transaksi = '"+NT_TextField_21552011440.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Diedit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Edit Data Gagal!!!"+e.getMessage());
        }
    NT_TextField_21552011440.setEnabled(true);
    loadData();
    AutoID();
    Bersih();
    }//GEN-LAST:event_ButtonEdit_21552011440ActionPerformed

    private void TBL_Penjualan_21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_Penjualan_21552011440MouseClicked
    int baris = TBL_Penjualan_21552011440.rowAtPoint(evt.getPoint());
        String tanggal_penjualan =TBL_Penjualan_21552011440.getValueAt(baris, 0).toString();
        dateChooserCombo_21552011440.setText(tanggal_penjualan);
        String no_transaksi =TBL_Penjualan_21552011440.getValueAt(baris, 1).toString();
        NT_TextField_21552011440.setText(no_transaksi);
        String id_pelanggan = TBL_Penjualan_21552011440.getValueAt(baris,2).toString();
        IDP_ComboBox_21552011440.setSelectedItem(id_pelanggan);
        String nama_pelanggan=TBL_Penjualan_21552011440.getValueAt(baris, 3).toString();
        NP_TextField_21552011440.setText(nama_pelanggan);
        String kode_barang=TBL_Penjualan_21552011440.getValueAt(baris, 4).toString();
        KB_ComboBox_21552011440.setSelectedItem(kode_barang);
        String nama_barang=TBL_Penjualan_21552011440.getValueAt(baris, 5).toString();
        NB_TextField_21552011440.setText(nama_barang);
        String stock=TBL_Penjualan_21552011440.getValueAt(baris, 6).toString();
        Stock_TextField_21552011440.setText(stock);
        String harga_satuan=TBL_Penjualan_21552011440.getValueAt(baris, 7).toString();
        HS_TextField_21552011440.setText(harga_satuan);
        String jumlah_jual =TBL_Penjualan_21552011440.getValueAt(baris, 8).toString();
        JJ_TextField_21552011440.setText(jumlah_jual);
        String total_harga =TBL_Penjualan_21552011440.getValueAt(baris, 9).toString();
        TH_TextField_21552011440.setText(total_harga);
        NT_TextField_21552011440.setEnabled(false);
    }//GEN-LAST:event_TBL_Penjualan_21552011440MouseClicked

    private void ButtonTotal_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTotal_21552011440ActionPerformed
    int harga, jumlah, total;

        harga = Integer.parseInt(HS_TextField_21552011440.getText());
        jumlah = Integer.parseInt(JJ_TextField_21552011440.getText());
        total =  harga*jumlah;
        TH_TextField_21552011440.setText(""+total);
    }//GEN-LAST:event_ButtonTotal_21552011440ActionPerformed

    private void CD_TextField_21552011440KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CD_TextField_21552011440KeyReleased
     String key=CD_TextField_21552011440.getText();
        System.out.println(key);  
        
        if(key!=""){
            cariData(key);
        }else{
            loadData();
        }
    }//GEN-LAST:event_CD_TextField_21552011440KeyReleased

    public final void loadData() {
        DefaultTableModel model = new DefaultTableModel();
        TBL_Penjualan_21552011440.setModel(model);
        model.addColumn("Tanggal Penjualan");
        model.addColumn("No Transaksi");
        model.addColumn("ID Pelanggan");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Stock");
        model.addColumn("Harga Satuan");
        model.addColumn("Jumlah Jual");
        model.addColumn("Total Harga");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM transaksi_jual";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[10];
                o[0] = r.getString("tanggal_penjualan");
                o[1] = r.getString("no_transaksi");
                o[2] = r.getString("id_pelanggan");
                o[3] = r.getString("nama_pelanggan");
                o[4] = r.getString("kode_barang");
                o[5] = r.getString("nama_barang");
                o[6] = r.getString("stock");
                o[7] = r.getObject("harga_satuan");
                o[8] = r.getString("jumlah_jual");
                o[9] = r.getString("total_harga");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terdapat Kesalahan, Harap Periksa Lagi");
        }
   }
        public final void loadTB() {
        DefaultTableModel model = new DefaultTableModel();
        TBL_Barang_21552011440.setModel(model);
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Stock");
        model.addColumn("Harga Awal");
        model.addColumn("Harga Satuan");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM barang";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[5];
                o[0] = r.getString("kode_barang");
                o[1] = r.getString("nama_barang");
                o[2] = r.getObject("stock");
                o[3] = r.getString("harga_awal");
                o[4] = r.getString("harga_satuan");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terdapat Kesalahan, Harap Periksa Lagi");
        }
   }
        public void AutoID() {
        try {
            String sql = "SELECT * FROM transaksi_jual ORDER BY no_transaksi DESC";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet rs=stm.executeQuery(sql);
            if (rs.next()) {
                String no_transaksi = rs.getString("no_transaksi").substring(2);
                String TJ = "" + (Integer.parseInt(no_transaksi) + 1);
                String No = "";

                if(TJ.length()==1)
                {No = "000";}
                else if(TJ.length()==2)
                {No = "00";}
                else if(TJ.length()==3)
                {No = "0";}
                else if(TJ.length()==4)
                {No = "";}
                NT_TextField_21552011440.setText("TJ" + No + TJ);
            } else {
                NT_TextField_21552011440.setText("TJ0001");
            }
            rs.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
        
        private void TampilCBID(){
            try {
            String sql = "select * from pelanggan";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                IDP_ComboBox_21552011440.addItem(res.getString("id_pelanggan"));
            }
        } catch (Exception e) {
        } 
    }
        private void TampilCBKB(){
            try {
            String sql = "select * from barang";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                KB_ComboBox_21552011440.addItem(res.getString("kode_barang"));
            }
        } catch (Exception e) {
        } 
    }
        private void TampilNB(){
            try {
            String sql = "select * from barang where kode_barang='"+KB_ComboBox_21552011440.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                NB_TextField_21552011440.setText(res.getString("nama_barang"));
            }
        } catch (Exception e) {
        } 
    }
        private void TampilStock(){
            try {
            String sql = "select * from barang where kode_barang='"+KB_ComboBox_21552011440.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                Stock_TextField_21552011440.setText(res.getString("stock"));
            }
        } catch (Exception e) {
        } 
    }
        private void TampilHarga(){
            try {
            String sql = "select * from barang where kode_barang='"+KB_ComboBox_21552011440.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                HS_TextField_21552011440.setText(res.getString("harga_satuan"));
            }
        } catch (Exception e) {
        } 
    }
        private void TampilNP(){
            try {
            String sql = "select * from pelanggan where id_pelanggan='"+IDP_ComboBox_21552011440.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                NP_TextField_21552011440.setText(res.getString("nama"));
            }
        } catch (Exception e) {
        } 
    }
        private void Bersih(){
            IDP_ComboBox_21552011440.setSelectedItem("");
            NP_TextField_21552011440.setText("");
            KB_ComboBox_21552011440.setSelectedItem("");
            NB_TextField_21552011440.setText("");
            Stock_TextField_21552011440.setText("");
            HS_TextField_21552011440.setText("");
            JJ_TextField_21552011440.setText("");
            TH_TextField_21552011440.setText("");
        }
    
        private void cariData(String key){
        try{
            DefaultTableModel model = new DefaultTableModel();
            Object[] judul_kolom = {"Tanggal Penjualan", "No Transaksi", "ID Pelanggan", "Nama Pelanggan", "Kode Barang", "Nama Barang", "Stock", "Harga Satuan", "Jumlah Jual", "Total Harga"};
            model=new DefaultTableModel(null,judul_kolom);
            TBL_Penjualan_21552011440.setModel(model);
            
            Connection conn=(Connection)Koneksi.configDB();
            Statement stt=conn.createStatement();
            model.getDataVector().removeAllElements();
            
            String sql = ("SELECT * from transaksi_jual WHERE no_transaksi LIKE '%"+key+"%' OR tanggal_penjualan LIKE '%"+key+"%' OR id_pelanggan LIKE '%"+key+"%' OR nama_pelanggan LIKE '%"+key+"%' OR kode_barang LIKE '%"+key+"%' OR nama_barang LIKE '%"+key+"%'");  
            ResultSet rs = stt.executeQuery(sql);
            while(rs.next()){
                Object[] data={
                    rs.getString("tanggal_penjualan"),
                    rs.getString("no_transaksi"),
                    rs.getString("id_pelanggan"),
                    rs.getString("nama_pelanggan"),
                    rs.getString("kode_barang"),
                    rs.getString("nama_barang"),         
                    rs.getString("stock"),
                    rs.getString("harga_satuan"),
                    rs.getString("jumlah_jual"),
                    rs.getString("total_harga")         
                };
               model.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEdit_21552011440;
    private javax.swing.JButton ButtonHapus_21552011440;
    private javax.swing.JButton ButtonLB_21552011440;
    private javax.swing.JButton ButtonTambah_21552011440;
    private javax.swing.JButton ButtonTotal_21552011440;
    private javax.swing.JTextField CD_TextField_21552011440;
    private javax.swing.JTextField HS_TextField_21552011440;
    private javax.swing.JComboBox<String> IDP_ComboBox_21552011440;
    private javax.swing.JTextField JJ_TextField_21552011440;
    private javax.swing.JComboBox<String> KB_ComboBox_21552011440;
    private javax.swing.JLabel LabelCD_21552011440;
    private javax.swing.JLabel LabelHS_21552011440;
    private javax.swing.JLabel LabelIDP_21552011440;
    private javax.swing.JLabel LabelINP_21552011440;
    private javax.swing.JLabel LabelInfo_21552011440;
    private javax.swing.JLabel LabelJJ_21552011440;
    private javax.swing.JLabel LabelJudul_21552011440;
    private javax.swing.JLabel LabelKDB_21552011440;
    private javax.swing.JLabel LabelNB_21552011440;
    private javax.swing.JLabel LabelNT_21552011440;
    private javax.swing.JLabel LabelStock_21552011440;
    private javax.swing.JLabel LabelTB_21552011440;
    private javax.swing.JLabel LabelTH_21552011440;
    private javax.swing.JLabel LabelTPen_77174961;
    private javax.swing.JTextField NB_TextField_21552011440;
    private javax.swing.JTextField NP_TextField_21552011440;
    private javax.swing.JTextField NT_TextField_21552011440;
    private javax.swing.JPanel PanelTB_21552011440;
    private javax.swing.JPanel Panel_21552011440;
    private javax.swing.JTextField Stock_TextField_21552011440;
    private javax.swing.JTable TBL_Barang_21552011440;
    private javax.swing.JTable TBL_Penjualan_21552011440;
    private javax.swing.JTextField TH_TextField_21552011440;
    private javax.swing.JDialog TabelBarang;
    private datechooser.beans.DateChooserCombo dateChooserCombo_21552011440;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
