/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master;

import Database.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MDena
 */
public class Pelanggan extends javax.swing.JInternalFrame {

    String JK;
    
    public Pelanggan() {
        initComponents();
        AutoID();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonJK_21552011440 = new javax.swing.ButtonGroup();
        Panel_21552011440 = new javax.swing.JPanel();
        ButtonTambah_21552011440 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_Pelanggan_21552011440 = new javax.swing.JTable();
        LabelNama_21552011440 = new javax.swing.JLabel();
        LabelJK_21552011440 = new javax.swing.JLabel();
        ID_TextField_21552011440 = new javax.swing.JTextField();
        LabelAlamat_21552011440 = new javax.swing.JLabel();
        LabelJudul_21552011440 = new javax.swing.JLabel();
        Nama_TextField_21552011440 = new javax.swing.JTextField();
        ButtonClear_21552011440 = new javax.swing.JButton();
        LabelID_21552011440 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Alamat_TextArea_21552011440 = new javax.swing.JTextArea();
        JKL_21552011440 = new javax.swing.JRadioButton();
        JKP_21552011440 = new javax.swing.JRadioButton();
        ButtonHapus_21552011440 = new javax.swing.JButton();
        ButtonEdit_21552011440 = new javax.swing.JButton();
        LabelCD_21552011440 = new javax.swing.JLabel();
        CD_TextField_21552011440 = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        ButtonTambah_21552011440.setText("Tambah");
        ButtonTambah_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambah_21552011440ActionPerformed(evt);
            }
        });

        TBL_Pelanggan_21552011440.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pelanggan", "Nama", "Jenis Kelamin", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBL_Pelanggan_21552011440.setEnabled(false);
        TBL_Pelanggan_21552011440.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_Pelanggan_21552011440MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_Pelanggan_21552011440);

        LabelNama_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelNama_21552011440.setText("Nama");

        LabelJK_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelJK_21552011440.setText("Jenis Kelamin");

        LabelAlamat_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelAlamat_21552011440.setText("Alamat");

        LabelJudul_21552011440.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        LabelJudul_21552011440.setText("DATA PELANGGAN");

        ButtonClear_21552011440.setText("Clear");
        ButtonClear_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClear_21552011440ActionPerformed(evt);
            }
        });

        LabelID_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelID_21552011440.setText("ID Pelanggan");

        Alamat_TextArea_21552011440.setColumns(20);
        Alamat_TextArea_21552011440.setRows(5);
        jScrollPane2.setViewportView(Alamat_TextArea_21552011440);

        ButtonJK_21552011440.add(JKL_21552011440);
        JKL_21552011440.setText("Laki-Laki");
        JKL_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JKL_21552011440ActionPerformed(evt);
            }
        });

        ButtonJK_21552011440.add(JKP_21552011440);
        JKP_21552011440.setText("Perempuan");
        JKP_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JKP_21552011440ActionPerformed(evt);
            }
        });

        ButtonHapus_21552011440.setText("Hapus");
        ButtonHapus_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapus_21552011440ActionPerformed(evt);
            }
        });

        ButtonEdit_21552011440.setText("Edit");
        ButtonEdit_21552011440.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEdit_21552011440ActionPerformed(evt);
            }
        });

        LabelCD_21552011440.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        LabelCD_21552011440.setText("Cari Data");

        CD_TextField_21552011440.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CD_TextField_21552011440KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel_21552011440Layout = new javax.swing.GroupLayout(Panel_21552011440);
        Panel_21552011440.setLayout(Panel_21552011440Layout);
        Panel_21552011440Layout.setHorizontalGroup(
            Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_21552011440Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelJudul_21552011440)
                .addGap(73, 73, 73)
                .addComponent(LabelCD_21552011440)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CD_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(Panel_21552011440Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_21552011440Layout.createSequentialGroup()
                        .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_21552011440Layout.createSequentialGroup()
                                .addComponent(LabelJK_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(102, 102, 102)
                                .addComponent(JKL_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JKP_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(Panel_21552011440Layout.createSequentialGroup()
                                .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_21552011440Layout.createSequentialGroup()
                                        .addComponent(LabelID_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(90, 90, 90))
                                    .addGroup(Panel_21552011440Layout.createSequentialGroup()
                                        .addComponent(LabelNama_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(Panel_21552011440Layout.createSequentialGroup()
                                        .addComponent(LabelAlamat_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Panel_21552011440Layout.createSequentialGroup()
                                        .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Panel_21552011440Layout.createSequentialGroup()
                                                .addComponent(ID_TextField_21552011440)
                                                .addGap(47, 47, 47))
                                            .addComponent(Nama_TextField_21552011440))
                                        .addGap(60, 60, 60))
                                    .addGroup(Panel_21552011440Layout.createSequentialGroup()
                                        .addComponent(ButtonClear_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(167, 167, 167))
                                    .addComponent(jScrollPane2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonTambah_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonEdit_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonHapus_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76))
                    .addGroup(Panel_21552011440Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(78, 78, 78))))
        );
        Panel_21552011440Layout.setVerticalGroup(
            Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_21552011440Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CD_TextField_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelCD_21552011440))
                    .addComponent(LabelJudul_21552011440))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_21552011440Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(ButtonTambah_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEdit_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonHapus_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(168, 168, 168))
                    .addGroup(Panel_21552011440Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID_TextField_21552011440)
                            .addComponent(LabelID_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nama_TextField_21552011440)
                            .addComponent(LabelNama_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_21552011440Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JKL_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JKP_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Panel_21552011440Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LabelJK_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_21552011440Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_21552011440Layout.createSequentialGroup()
                                .addComponent(LabelAlamat_21552011440, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(104, 104, 104))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonClear_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_21552011440, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 582, 563);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTambah_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambah_21552011440ActionPerformed
        try {
            String sql = "INSERT INTO pelanggan VALUES ('"+ID_TextField_21552011440.getText()+"','"
                    +Nama_TextField_21552011440.getText()+"','"
                    +JK+"','"
                    +Alamat_TextArea_21552011440.getText()+"')";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil DiMasukan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       ID_TextField_21552011440.setEnabled(true); 
       loadData();
       AutoID();
       Bersih();
    }//GEN-LAST:event_ButtonTambah_21552011440ActionPerformed

    private void JKL_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JKL_21552011440ActionPerformed
    JK="Laki-Laki";
    }//GEN-LAST:event_JKL_21552011440ActionPerformed

    private void JKP_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JKP_21552011440ActionPerformed
    JK="Perempuan";
    }//GEN-LAST:event_JKP_21552011440ActionPerformed

    private void TBL_Pelanggan_21552011440MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_Pelanggan_21552011440MouseClicked
     int baris = TBL_Pelanggan_21552011440.rowAtPoint(evt.getPoint());
        String id_pelanggan =TBL_Pelanggan_21552011440.getValueAt(baris, 0).toString();
        ID_TextField_21552011440.setText(id_pelanggan);
        String nama = TBL_Pelanggan_21552011440.getValueAt(baris,1).toString();
        Nama_TextField_21552011440.setText(nama);
        String alamat=TBL_Pelanggan_21552011440.getValueAt(baris, 3).toString();
        Alamat_TextArea_21552011440.setText(alamat);
        ID_TextField_21552011440.setEnabled(false);
    }//GEN-LAST:event_TBL_Pelanggan_21552011440MouseClicked

    private void ButtonHapus_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapus_21552011440ActionPerformed
    try {
            String sql ="delete from pelanggan where id_pelanggan='"+ID_TextField_21552011440.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    ID_TextField_21552011440.setEnabled(true);
    loadData();
    AutoID();
    Bersih();
    }//GEN-LAST:event_ButtonHapus_21552011440ActionPerformed

    private void ButtonEdit_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEdit_21552011440ActionPerformed
    try {
            String sql ="UPDATE pelanggan SET id_pelanggan = '"+ID_TextField_21552011440.getText()+
                    "',nama = '"+Nama_TextField_21552011440.getText()+
                    "',jenis_kelamin= '"+JK+
                    "',alamat= '"+Alamat_TextArea_21552011440.getText()+
                    "' WHERE id_pelanggan = '"+ID_TextField_21552011440.getText()+"'";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Diedit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Edit Data Gagal!!!"+e.getMessage());
        }
    ID_TextField_21552011440.setEnabled(true);
    loadData();
    AutoID();
    Bersih();
    }//GEN-LAST:event_ButtonEdit_21552011440ActionPerformed

    private void ButtonClear_21552011440ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClear_21552011440ActionPerformed
    Bersih();
    }//GEN-LAST:event_ButtonClear_21552011440ActionPerformed

    private void CD_TextField_21552011440KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CD_TextField_21552011440KeyReleased
        String key=CD_TextField_21552011440.getText();
        System.out.println(key);

        if(key!=""){
            cariData(key);
        }else{
            loadData();
        }
    }//GEN-LAST:event_CD_TextField_21552011440KeyReleased

    public final void loadData() {
        DefaultTableModel model = new DefaultTableModel();
        TBL_Pelanggan_21552011440.setModel(model);
        model.addColumn("ID Pelanggan");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = Koneksi.configDB();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM pelanggan";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[4];
                o[0] = r.getString("id_pelanggan");
                o[1] = r.getString("nama");
                o[2] = r.getString("jenis_kelamin");
                o[3] = r.getString("alamat");
               
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
   }
    
    private void cariData(String key){
        try{
            DefaultTableModel model = new DefaultTableModel();
            Object[] judul_kolom = {"ID Pelanggan", "Nama", "Jenis Kelamin", "Alamat"};
            model=new DefaultTableModel(null,judul_kolom);
            TBL_Pelanggan_21552011440.setModel(model);
            
            Connection conn=(Connection)Koneksi.configDB();
            Statement stt=conn.createStatement();
            model.getDataVector().removeAllElements();
            
            String sql = ("SELECT * from pelanggan WHERE id_pelanggan LIKE '%"+key+"%' OR nama LIKE '%"+key+"%'");  
            ResultSet rs = stt.executeQuery(sql);
            while(rs.next()){
                Object[] data={
                    rs.getString("id_pelanggan"),
                    rs.getString("nama"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("alamat"),
                };
               model.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    
    public void AutoID() {
        try {
            String sql = "SELECT * FROM pelanggan ORDER BY id_pelanggan DESC";
            java.sql.Connection conn=(Connection)Koneksi.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet rs=stm.executeQuery(sql);
            if (rs.next()) {
                String id_pelanggan = rs.getString("id_pelanggan").substring(3);
                String IDP = "" + (Integer.parseInt(id_pelanggan) + 1);
                String No = "";

                if(IDP.length()==1)
                {No = "000";}
                else if(IDP.length()==2)
                {No = "00";}
                else if(IDP.length()==3)
                {No = "0";}
                else if(IDP.length()==4)
                {No = "";}
                ID_TextField_21552011440.setText("IDP" + No + IDP);
            } else {
                ID_TextField_21552011440.setText("IDP0001");
            }
            rs.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void Bersih(){
        Nama_TextField_21552011440.setText("");
        Alamat_TextArea_21552011440.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat_TextArea_21552011440;
    private javax.swing.JButton ButtonClear_21552011440;
    private javax.swing.JButton ButtonEdit_21552011440;
    private javax.swing.JButton ButtonHapus_21552011440;
    private javax.swing.ButtonGroup ButtonJK_21552011440;
    private javax.swing.JButton ButtonTambah_21552011440;
    private javax.swing.JTextField CD_TextField_21552011440;
    private javax.swing.JTextField ID_TextField_21552011440;
    private javax.swing.JRadioButton JKL_21552011440;
    private javax.swing.JRadioButton JKP_21552011440;
    private javax.swing.JLabel LabelAlamat_21552011440;
    private javax.swing.JLabel LabelCD_21552011440;
    private javax.swing.JLabel LabelID_21552011440;
    private javax.swing.JLabel LabelJK_21552011440;
    private javax.swing.JLabel LabelJudul_21552011440;
    private javax.swing.JLabel LabelNama_21552011440;
    private javax.swing.JTextField Nama_TextField_21552011440;
    private javax.swing.JPanel Panel_21552011440;
    private javax.swing.JTable TBL_Pelanggan_21552011440;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
